ExamenTrueHome/Controllers/PropertiesController.cs
using ExamenTrueHome.DataAccess.Repository;
using ExamenTrueHome.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenTrueHome.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PropertiesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.ExistInActivity = false;
            return View();
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var a = _unitOfWork.Property.GetAll(includeProperties:"Status");
            return Json(new { data = a });
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Property property)
        {
            if (ModelState.IsValid)
            {
                property.Created_At = DateTime.Now;
                property.Status_Id = 1;
                _unitOfWork.Property.Add(property);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            PropertyViewModel property = new PropertyViewModel()
            {
                Property = new Property(),
                Statuses = _unitOfWork.Status.GetListItems()
            };
            property.Property = _unitOfWork.Property.Get(id);
            if (property.Property == null)
                return NotFound();

            return View(property);
        }

        [HttpPost]
        public IActionResult Edit(PropertyViewModel propertyViewModel)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Property.Update(propertyViewModel.Property);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var exist = _unitOfWork.Property.ExistInActivity(id);
            return Json(exist);

        }

        [HttpDelete]
        public IActionResult DeleteConfirm(int id)
        {
            _unitOfWork.Property.Remove(id);
            _unitOfWork.Save();
            return Json(new {data = true });
        }

    }
}

ExamenTrueHome/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenTrueHome</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Examen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Actividades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Properties" asp-action="Index">Propiedades</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ExamenTrueHome - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>